# Generated by Django 4.1.1 on 2022-09-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.IntegerField()),
            ],
            options={
                'db_table': 'Composition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=20)),
                ('KPFC', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Name', models.CharField(max_length=40)),
                ('Category', models.CharField(max_length=50)),
                ('Cooking_time', models.TimeField()),
                ('Level', models.IntegerField()),
                ('KPFC', models.CharField(max_length=50)),
                ('Vegan', models.BinaryField()),
            ],
            options={
                'db_table': 'Recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('Birth_date', models.DateField()),
                ('Phone', models.CharField(max_length=20)),
                ('E-mail', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
